### ISSUE TITLE
simple commands to be able to post links about a topic to a user

### ISSUE THREAD

**Issue by lsmith77** [kubernetes-sigs/slack-infra#12]
f.e. `/inclusion coc`, `/inclusion guys`

each key word could be associated with a list of links that is then send to the given channel

also optionally the link can be send via DM to a specific user

`/inclusion @foo coc`

rather than a command this could also be done via the message context menu to be able to tell the user why they are getting the giving message, ie.

`Your message "..." promoted someone to send you the link to the code of conduct ..`

**Comment by jeefy** [comment]
I'm torn on this idea. 

I like the idea of having templated messages for some topics. I also think it could be abused and, thus, locked down to certain users. 

This might be something we can look into/build out once GitHub->Slack identity is implemented.

**Comment by lsmith77** [comment]
maybe this should also have a moderation step .. ie. before sending the message a moderator needs to approve. this moderator would also be presented context information and maybe some metrics on the user about previous cases where someone selected a message of theirs
