### ISSUE TITLE
Unable to type in the Reporter UI

### ISSUE THREAD

**Issue by nikhita** [kubernetes-sigs/slack-infra#13]
When I type something in the Reporter UI, each subsequent character starts with a newline.

Screenshot:

![Screenshot from 2019-05-13 17-42-29](https://user-images.githubusercontent.com/16105680/57620634-fa8bd600-75a6-11e9-8598-43d186174ce6.png)

**Comment by Katharine** [comment]
We have no control over this UI. All we do is ask Slack to show a text box and then it does what it wants. 

FWIW I've never seen this in the web app on Linux Chrome, the Mac app, or the iOS or Android apps.

**Comment by nikhita** [comment]
> FWIW I've never seen this in the web app on Linux Chrome, the Mac app, or the iOS or Android apps.

I get this on the native Linux client (which is supposed to be beta). And I just checked this on the webapp on Firefox and it worked fine. :+1: 

I'll close this then, and submit a bug report to Slack.

/close
