### ISSUE TITLE
Move to slack's new conversations API

### ISSUE THREAD

**Issue by castrojo** [kubernetes-sigs/slack-infra#37]
From Katharine  in slack: 
Apparently the welcomer bot uses a deprecated API, nothing else does , looks like it’s just this line that needs changing: 

https://github.com/kubernetes-sigs/slack-infra/blob/master/slack-welcomer/handler.go#L133

**Comment by mrbobbytables** [comment]
Here is the deprecation information
https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api

**Comment by palnabarun** [comment]
@castrojo @mrbobbytables -- Can I take this up? :)

**Comment by phumberdroz** [comment]
Of course you can @palnabarun :)

**Comment by mrbobbytables** [comment]
cc @pymander
He was interested in helping too :)

**Comment by pymander** [comment]
It looks like a pretty simple change, and I am happy to let @palnabarun take it.

**Comment by palnabarun** [comment]
@pymander @mrbobbytables -- I took a dig at it last weekend. The change needed is indeed simple.

I am wondering if there is a way I can test the change without setting up the whole bot in a new Slack workspace like described in [docs/app-creation.md](https://github.com/kubernetes-sigs/slack-infra/blob/master/docs/app-creation.md). What do you think?
