### ISSUE TITLE
Missing source for slackin

### ISSUE THREAD

**Issue by spiffxp** [kubernetes-sigs/slack-infra#40]
It was addd to k8s.io via https://github.com/kubernetes/k8s.io/pull/192

It was removed from k8s.io via https://github.com/kubernetes/k8s.io/pull/226

We're currently referencing an image hosted in the google.com kubernetes-tools project: https://github.com/kubernetes/k8s.io/issues/1466#issuecomment-740182422

We should migrate this to the community-owned k8s-staging-slack-infra repository

**Comment by Katharine** [comment]
The source of the image is https://github.com/Katharine/slackin/tree/dns-filter (note: not the master branch).

**Comment by nikhita** [comment]
/reopen
/remove-lifecycle rotten

cc @cpanato
