### ISSUE TITLE
Migrate to new default branch name

### ISSUE THREAD

**Issue by spiffxp** [kubernetes-sigs/slack-infra#50]
Part of umbrella issue to rename default branches: https://github.com/kubernetes/org/issues/2222

Copy-pasted checklist from https://raw.githubusercontent.com/kubernetes/community/master/github-management/default-branch-migration.md

## Changes pre-rename

Make the following changes _before_ renaming the branch the `master` branch.

Note: There might be additional changes required that have not been
covered in this checklist.

### Anytime

These changes are **non-disruptive**  and can be made anytime before
renaming the branch.

- [x] If a prowjob triggers on the `master` branch (`branches` field
of the prowjob), add the `main` branch to the list
(see [kubernetes/test-infra#20665] for an example).
  - searched for jobs: https://cs.k8s.io/?q=slack-infra&i=nope&files=config%2Fjobs&excludeFiles=&repos=kubernetes/test-infra
  - opened PR: https://github.com/kubernetes/test-infra/pull/21607

- [x] If the [`milestone_applier`] prow config references the `master` branch,
add the `main` branch to the config (see [kubernetes/test-infra#20675] for an example).
  - n/a - no milestone_applier setting

- [x] If the [`branch_protection`] prow config references the `master` branch,
add the `main` branch to the config.
  - n/a - no branch_protection setting

### Just before rename

These changes are **disruptive** and should be made just before
renaming the branch.

- [x] If a prowjob mentions the `master` branch in `base_ref`,
update it to the `main` branch. For a periodic job, ensure that
the branch is renamed between periodic job runs.
  - n/a - no jobs do this

- [x] If a prowjob mentions `master` in its name, rename the job to
to not include the branch name. [`status-reconciler`] should automatically
migrate the PR status contexts to the new job name but this has not been tested yet.
The job with the new name will also appear as a differt job in Testgrid.
  - n/a - no slack-infra jobs do this

- [x] If a prowjob calls scripts or code in your repo that explicitly
reference `master`, update all references to use `main`.

- [x] If the repo has netlify configured for it, ask a member of the GitHub
Management Team to rename the `master` branch to `main` in the netlify site config.
It can't be controlled through the netlify config in the repo.
  - n/a - no netlify

### Approval

- [x] Once all non-disruptive tasks have been completed and disruptive tasks
have been identified, assign the GitHub Management team ([@kubernetes/owners])
for approval.
  - verbally asked during github management meeting

## Rename the default branch

- [x] Rename the default branch from `master` to `main` using the GitHub UI
by following the [official instructions].
  - confirmed no prowjob retriggers when clicking the button, reported on https://github.com/kubernetes/test-infra/issues/20829 and closed that issue

## Changes post-rename

After the default branch has been renamed to `main`, make the following
changes.

Note: There might be additional changes required that have not been
covered in this checklist.

### Prowjobs

- [x] If a prowjob still references the `master` branch in the `branches` field,
remove the `master` branch (see [kubernetes/test-infra#20669] for an example).
  - https://github.com/kubernetes/test-infra/pull/21617

### Prow config

- [x] If the [`milestone_applier`] prow config references the `master` branch,
remove it from the config.
  - n/a

- [x] If the [`branch_protection`] prow config references the `master` branch,
remove it from the config.
  - n/a

### Other

- [x] If any docs reference the `master` branch, update to `main`
(URLs will be automatically redirected).
  - https://github.com/kubernetes/community/pull/5687

- [x] Ensure that CI and PR tests work fine.
  - ran /test all on a sample PR
  - merged a sample PR
  - no periodics/postsubmits to test

- [x] Trial the local development experience with a pre-rename clone.
  - did so

- [x] Send a notice about the branch rename to your SIG's mailing list.
Include the link to the [GitHub instructions to rename your local branch].
  - https://groups.google.com/g/kubernetes-sig-contribex/c/rRnvJh2WROc/m/acEQqPODAQAJ

/assign
/sig contributor-experience
/kind cleanup

**Comment by nikhita** [comment]
+1 from github management team hat on

**Comment by spiffxp** [comment]
I've been updating description as I go.  Dropped TODO's on what remains.  I'm going to try and update k/community docs before closing this out.  I'll post further updates as comments, not just description edits

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/community/pull/5687 and https://github.com/kubernetes/test-infra/pull/21617 to close out the actual rename part of this, leaving notification, and then updating the branch rename docs as a followup

**Comment by spiffxp** [comment]
/close
Mailing list notification sent: https://groups.google.com/g/kubernetes-sig-contribex/c/rRnvJh2WROc/m/acEQqPODAQAJ

No remaining references to the old branch: https://cs.k8s.io/?q=slack-infra.*master&i=nope&files=&excludeFiles=&repos=
