### ISSUE TITLE
feature request: slackbot for group chairs/leads

### ISSUE THREAD

**Issue by parispittman** [kubernetes-sigs/slack-infra#55]
-this is a draft/wip-

what
slackbot to remind community groups of important things in the community on a consistent, automated basis. only for #chairs-and-techleads channel. 

why
why slack bot - taking out the human and the terrible calendaring. 
why reminder - there is a lot and we forget because we are human 

things?
- have you uploaded videos this month?
- have you scrubbed owners files this year? / run maintainers tooling?
- who stands out in the last 3 months as someone to be promoted to member/reviewer/approver/chair/role?
- annual report kick off / deadline approaching
- kubecon maintainer track submissions are due / started
- did your group shoutout anyone in the #shoutouts channel?

**Comment by parispittman** [comment]
this was an anonymous tip/suggestion and frankly, a great one. whoever you are out there, thank you. :p

**Comment by mrbobbytables** [comment]
Reminders are possible in slack already, we use them for the biweekly slack standup meetings in sig-contribex

**Comment by parispittman** [comment]
reminders could be ok for this as an interim solution but ultimately I think a bot would be best and the marketing team and other folks can contribute to it vs needing to remember if we set a reminder vs didn't, etc.

**Comment by mrbobbytables** [comment]
so essentially the twitter bot but for slack?

**Comment by chases2** [comment]
Would chairs and techleads configure which reminders they want, or is there some definite subset of reminders that every chair and techlead should get?
