### ISSUE TITLE
moderate-words logs all events

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/slack-infra#56]
This is super wasteful 😱 

Right now it's down due to https://github.com/kubernetes/community/issues/6841 so it's not logging at the moment.

We should only log relevant debug info, not every single event processed in full. None of the other tools in this repo do this.

**Comment by BenTheElder** [comment]
cc @cpanato

**Comment by BenTheElder** [comment]
/lifecycle frozen
this is still super wasteful

**Comment by jmhbnz** [comment]
/assign

Thanks for raising this @BenTheElder, I've had a go at a fix via #62.

**Comment by BenTheElder** [comment]
/reopen
@jeefy we still need to get this change deployed into k8s infra cc @ameukam less logging costs for k8s infra :+)

**Comment by BenTheElder** [comment]
I don't think we've deployed a new build for 3+ years now https://github.com/kubernetes/k8s.io/blob/main/apps/slack-infra/resources/slack-moderator-words/deployment.yaml

**Comment by BenTheElder** [comment]
xref: #66

**Comment by BenTheElder** [comment]
This is actually fixed now.
